---
title: "First Import (Draft)"
output: 
  html_document:
    toc: true
    toc_float: true
    code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = F,
                      message = F)
```


# Library loading
```{r}
library(trackeR)
library(ggplot2)
library(ggmap)
library(tidyverse)
library(googledrive)
library(emojifont)
```

# download google fit archives from takeout

archives are generated manually, stored on personnal google drive and downloaded in ´data´ folder

```{r}
archive_list <- googledrive::drive_find("takeout")

archives <- archive_list$drive_resource

filesname <- c()
filesdate <- c()
for (f in c(1:length(archives))){
  filename <- archives[[f]]$name
  filedate <- archives[[f]]$createdTime
  filesname <- c(filesname, filename)
  filesdate <- c(filesdate, filedate)
}

list_files <- data_frame(filesname, 
                         filesdate) %>% 
  mutate(filesdate=as.POSIXct(filesdate,
                              format="%Y-%m-%dT%H:%M:%S"))

id_to_dowload <- list_files %>% 
  filter(filesdate==max(list_files$filesdate)) %>%
  pull(filesname)

googledrive::drive_download(id_to_dowload,path = "data/data.zip",overwrite = T)

unzip("data/data.zip",exdir = "data/")

data_path <- "data/Takeout/Fit/Activités/"
file_list <- list.files(data_path,pattern = ".tcx$")

df <- data_frame(activity = file_list) %>%
  mutate(file_contents = map(activity,      
           ~ readTCX(file.path(data_path, .))) 
  ) %>% unnest(.) %>% group_by(activity) %>% fill(latitude) %>% fill(longitude) %>% fill(altitude)
```


# Visualize data
```{r, dpi=250}
ggplot(df,aes(longitude, latitude))+
  coord_quickmap(expand = T)+
  geom_point(aes(color=as.numeric(altitude)))+
  labs(color="Altitude (m)")+
  scale_color_distiller(direction = 1)+
scale_y_continuous(expand=expand_scale(mult=c(0.15,0.15),add=c(0.00,00)))+
    scale_x_continuous(expand=c(0.00,0.0005))+
  geom_text(data= df  %>% 
              filter(time==max(time)) %>% 
                       mutate(label=emoji('checkered_flag')),aes(label=label),
            family="OpenSansEmoji",
                           size=3.5,
            col="white")+
     geom_text(data= df  %>% 
              filter(time==min(time)) %>% 
                       mutate(label=emoji('triangular_flag_on_post')),
              aes(label=label),
            family="OpenSansEmoji",
            col="white",
            size=3.5)+
  facet_wrap(~activity,scales = "free")+
  theme_void()+
  theme(plot.background = element_rect(color = "black", fill = "black"),
        panel.background = element_rect(fill = "black", color="white"),
        text = element_text(color="white"),
        plot.margin = unit(c(1,1,1,1),"cm"),
        legend.position = "bottom",
        plot.title = element_text(hjust=0.5))
  
```


```{r, eval=F}
#Not working because of firewall
mapImage <- get_map(location = c(lon = mean(df$lon) - 0.05, lat = mean(df$lat)),
                    source = "google",
                    maptype = "toner",
                    zoom = 10)
 
ggmap(mapImage, extent = "device") + 
  geom_point(aes(x = lon,
                 y = lat),
             data = df,
             colour = "red3",
             size = .2) 
```

